### PR TITLE
fix: move @sentry/sveltekit to production dependencies

### PR DESCRIPTION
**Pull request by thenbe**

### CODE REVIEW

**Comment by hrueger** [comment]
Hi, thanks for the PR. I basically tried the same thing earlier, don't know why it was not working there.

**Comment by thenbe** [comment]
> Hi, thanks for the PR. I basically tried the same thing earlier, don't know why it was not working there.

You know, the same thing happened me. I believe it's due to the fact that your build script does not do a proper clean up before building, and that some artifacts from the the previous trial(s) are being leftover.

```diff
- "build": "vite build"
+ "build": "rm -rf ./{.svelte-kit,build} && svelte-kit sync && vite build"
```

**Comment by thenbe** [comment]
@hrueger One final thing, you might want to look into `pnpm` (the [`pnpm deploy`](https://pnpm.io/cli/deploy) command in particular) if you're going to rely on this pattern. It's much faster for exactly this sort of stuff.

**Comment by hrueger** [comment]
Cool, I did not know about this. Thanks for the hint!

**Pull request closed without merging**
